import { type NextPage } from "next";
import Head from "next/head";
import {
  About,
  Contact,
  Hero,
  Projects,
  Skills,
} from "../components/Home/sections";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Golf Grab</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center  bg-base-200">
        <Hero />
        <About />
        <Skills />
        <Projects />
        <Contact />
      </main>
    </>
  );
};

export default Home;
