import { type NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import { InView } from "react-intersection-observer";
import type { SectionType } from "../components/Home/sections";
import {
  About,
  Contact,
  Hero,
  Projects,
  Skills,
} from "../components/Home/sections";
import Layout from "../components/Layout";
import { SectionContext } from "../contexts/SectionContext";

const sectionElements: { key: SectionType; value: JSX.Element }[] = [
  { key: "Hero", value: <Hero /> },
  { key: "About", value: <About /> },
  { key: "Skills", value: <Skills /> },
  { key: "Projects", value: <Projects /> },
  { key: "Contact", value: <Contact /> },
];

const Home: NextPage = () => {
  const { setSection } = useContext(SectionContext);
  return (
    <>
      <Layout>
        <Head>
          <title>Golf Grab</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center  bg-base-200">
          {sectionElements.map((sectionElement) => (
            <InView
              key={sectionElement.key}
              threshold={0.5}
              onChange={(inView) => {
                if (inView) {
                  setSection?.(sectionElement.key);
                }
              }}
            >
              {sectionElement.value}
            </InView>
          ))}
        </main>
      </Layout>
    </>
  );
};

export default Home;
