import { type NextPage } from "next";
import Head from "next/head";
import { useContext } from "react";
import type { SectionType } from "../components/Home/sections";
import {
  About,
  Contact,
  Hero,
  Projects,
  Skills,
} from "../components/Home/sections";
import SectionTracker from "../components/Home/utils/SectionTracker";
import Layout from "../components/Layout";
import { SectionContext } from "../contexts/SectionContext";

const sectionElements: {
  sectionName: SectionType;
  component: React.ReactNode;
}[] = [
  { sectionName: "Hero", component: <Hero /> },
  { sectionName: "About", component: <About /> },
  { sectionName: "Skills", component: <Skills /> },
  { sectionName: "Projects", component: <Projects /> },
  { sectionName: "Contact", component: <Contact /> },
];

const Home: NextPage = () => {
  const { setSection } = useContext(SectionContext);
  return (
    <>
      <Layout>
        <Head>
          <title>Golf Grab</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center  bg-base-200">
          {sectionElements.map((sectionElement) => (
            <SectionTracker
              key={sectionElement.sectionName}
              sectionName={sectionElement.sectionName}
              setSection={setSection}
            >
              {sectionElement.component}
            </SectionTracker>
          ))}
        </main>
      </Layout>
    </>
  );
};

export default Home;
